[package]
name = "imgui-cpp-sys"
version = "0.1.0"
authors = ["David <dn@vestico.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
